const { MongoClient } = require("mongodb");
require("dotenv").config();

const uri = process.env.MONGO_URI || "mongodb://127.0.0.1:27017";
const client = new MongoClient(uri);
const dbName = "Zoidinc";


const products = [
  {
    "name": "Smartphones Product 1",
    "description": "Description for Smartphones Product 1",
    "price": 579.89,
    "rating": 2.8,
    "brand": "Brand for Smartphones Product 1",
    "images": "'[\"/images/smartphones1_1.jpg\"",
    "stock_quantity": "\"/images/smartphones1_2.jpg\"]'",
    "colors_available": 15,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"L\"",
    "availability": "\"S\"]'",
    "subcategoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039",    "categoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039"

  },
  {
    "name": "Smartphones Product 2",
    "description": "Description for Smartphones Product 2",
    "price": 53.03,
    "rating": 3.6,
    "brand": "Brand for Smartphones Product 2",
    "images": "'[\"/images/smartphones2_1.jpg\"",
    "stock_quantity": "\"/images/smartphones2_2.jpg\"]'",
    "colors_available": 34,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"White\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"M\"",
    "availability": "\"L\"]'",
    "subcategoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039",  "categoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039"
  },
  {
    "name": "Smartphones Product 3",
    "description": "Description for Smartphones Product 3",
    "price": 724.76,
    "rating": 3.9,
    "brand": "Brand for Smartphones Product 3",
    "images": "'[\"/images/smartphones3_1.jpg\"",
    "stock_quantity": "\"/images/smartphones3_2.jpg\"]'",
    "colors_available": 48,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"M\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039",  "categoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039"
  },
  {
    "name": "Smartphones Product 4",
    "description": "Description for Smartphones Product 4",
    "price": 520.33,
    "rating": 3.8,
    "brand": "Brand for Smartphones Product 4",
    "images": "'[\"/images/smartphones4_1.jpg\"",
    "stock_quantity": "\"/images/smartphones4_2.jpg\"]'",
    "colors_available": 80,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039",  "categoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039"
  },
  {
    "name": "Smartphones Product 5",
    "description": "Description for Smartphones Product 5",
    "price": 225.63,
    "rating": 5.0,
    "brand": "Brand for Smartphones Product 5",
    "images": "'[\"/images/smartphones5_1.jpg\"",
    "stock_quantity": "\"/images/smartphones5_2.jpg\"]'",
    "colors_available": 69,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"L\"",
    "availability": "\"S\"]'",
    "subcategoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039",  "categoryId": "998a1da3-8655-4aee-b4da-2fe5bfae4039"
  },
  {
    "name": "Laptops Product 1",
    "description": "Description for Laptops Product 1",
    "price": 642.08,
    "rating": 4.7,
    "brand": "Brand for Laptops Product 1",
    "images": "'[\"/images/laptops1_1.jpg\"",
    "stock_quantity": "\"/images/laptops1_2.jpg\"]'",
    "colors_available": 73,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"White\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"XL\"",
    "categoryId": "de5c7f01-c4a5-4d60-abd7-3a512acc73b9",
    "subcategoryId": "e27ebd9f-3175-4026-940b-2fb566e87d81"
  },
  {
    "name": "Laptops Product 2",
    "description": "Description for Laptops Product 2",
    "price": 784.79,
    "rating": 4.4,
    "brand": "Brand for Laptops Product 2",
    "images": "'[\"/images/laptops2_1.jpg\"",
    "stock_quantity": "\"/images/laptops2_2.jpg\"]'",
    "colors_available": 37,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Red\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"M\"",
    "availability": "\"S\"]'",    "categoryId": "de5c7f01-c4a5-4d60-abd7-3a512acc73b9",

    "subcategoryId": "e27ebd9f-3175-4026-940b-2fb566e87d81"
  },
  {
    "name": "Laptops Product 3",
    "description": "Description for Laptops Product 3",
    "price": 10.79,
    "rating": 3.7,
    "brand": "Brand for Laptops Product 3",
    "images": "'[\"/images/laptops3_1.jpg\"",
    "stock_quantity": "\"/images/laptops3_2.jpg\"]'",
    "colors_available": 10,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Black\"",
    "features": "\"White\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",    "categoryId": "de5c7f01-c4a5-4d60-abd7-3a512acc73b9",

    "subcategoryId": "e27ebd9f-3175-4026-940b-2fb566e87d81"
  },
  {
    "name": "Laptops Product 4",
    "description": "Description for Laptops Product 4",
    "price": 313.25,
    "rating": 4.2,
    "brand": "Brand for Laptops Product 4",
    "images": "'[\"/images/laptops4_1.jpg\"",
    "stock_quantity": "\"/images/laptops4_2.jpg\"]'",
    "colors_available": 23,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",    "categoryId": "de5c7f01-c4a5-4d60-abd7-3a512acc73b9",

    "subcategoryId": "e27ebd9f-3175-4026-940b-2fb566e87d81"
  },
  {
    "name": "Laptops Product 5",
    "description": "Description for Laptops Product 5",
    "price": 493.94,
    "rating": 4.2,
    "brand": "Brand for Laptops Product 5",
    "images": "'[\"/images/laptops5_1.jpg\"",
    "stock_quantity": "\"/images/laptops5_2.jpg\"]'",
    "colors_available": 37,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Green\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",    "categoryId": "de5c7f01-c4a5-4d60-abd7-3a512acc73b9",

    "subcategoryId": "e27ebd9f-3175-4026-940b-2fb566e87d81"
  },
  {
    "name": "Headphones Product 1",
    "description": "Description for Headphones Product 1",
    "price": 255.62,
    "rating": 2.8,
    "brand": "Brand for Headphones Product 1",
    "images": "'[\"/images/headphones1_1.jpg\"",
    "stock_quantity": "\"/images/headphones1_2.jpg\"]'",
    "colors_available": 62,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"White\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "1394e704-6bf9-4e51-8137-bd70f657efdd"
  },
  {
    "name": "Headphones Product 2",
    "description": "Description for Headphones Product 2",
    "price": 637.18,
    "rating": 4.6,
    "brand": "Brand for Headphones Product 2",
    "images": "'[\"/images/headphones2_1.jpg\"",
    "stock_quantity": "\"/images/headphones2_2.jpg\"]'",
    "colors_available": 65,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "1394e704-6bf9-4e51-8137-bd70f657efdd"
  },
  {
    "name": "Headphones Product 3",
    "description": "Description for Headphones Product 3",
    "price": 275.1,
    "rating": 3.1,
    "brand": "Brand for Headphones Product 3",
    "images": "'[\"/images/headphones3_1.jpg\"",
    "stock_quantity": "\"/images/headphones3_2.jpg\"]'",
    "colors_available": 96,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Red\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "1394e704-6bf9-4e51-8137-bd70f657efdd"
  },
  {
    "name": "Headphones Product 4",
    "description": "Description for Headphones Product 4",
    "price": 254.47,
    "rating": 3.1,
    "brand": "Brand for Headphones Product 4",
    "images": "'[\"/images/headphones4_1.jpg\"",
    "stock_quantity": "\"/images/headphones4_2.jpg\"]'",
    "colors_available": 19,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Black\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "1394e704-6bf9-4e51-8137-bd70f657efdd"
  },
  {
    "name": "Headphones Product 5",
    "description": "Description for Headphones Product 5",
    "price": 432.57,
    "rating": 3.3,
    "brand": "Brand for Headphones Product 5",
    "images": "'[\"/images/headphones5_1.jpg\"",
    "stock_quantity": "\"/images/headphones5_2.jpg\"]'",
    "colors_available": 71,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Black\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"M\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "1394e704-6bf9-4e51-8137-bd70f657efdd"
  },
  {
    "name": "Shirts Product 1",
    "description": "Description for Shirts Product 1",
    "price": 767.66,
    "rating": 2.8,
    "brand": "Brand for Shirts Product 1",
    "images": "'[\"/images/shirts1_1.jpg\"",
    "stock_quantity": "\"/images/shirts1_2.jpg\"]'",
    "colors_available": 73,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Green\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "c2018722-9a65-481c-bae8-be72a0293fcc"
  },
  {
    "name": "Shirts Product 2",
    "description": "Description for Shirts Product 2",
    "price": 688.47,
    "rating": 2.7,
    "brand": "Brand for Shirts Product 2",
    "images": "'[\"/images/shirts2_1.jpg\"",
    "stock_quantity": "\"/images/shirts2_2.jpg\"]'",
    "colors_available": 56,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "c2018722-9a65-481c-bae8-be72a0293fcc"
  },
  {
    "name": "Shirts Product 3",
    "description": "Description for Shirts Product 3",
    "price": 694.6,
    "rating": 4.3,
    "brand": "Brand for Shirts Product 3",
    "images": "'[\"/images/shirts3_1.jpg\"",
    "stock_quantity": "\"/images/shirts3_2.jpg\"]'",
    "colors_available": 28,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Black\"",
    "features": "\"White\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",
    "subcategoryId": "c2018722-9a65-481c-bae8-be72a0293fcc"
  },
  {
    "name": "Shirts Product 4",
    "description": "Description for Shirts Product 4",
    "price": 857.35,
    "rating": 4.9,
    "brand": "Brand for Shirts Product 4",
    "images": "'[\"/images/shirts4_1.jpg\"",
    "stock_quantity": "\"/images/shirts4_2.jpg\"]'",
    "colors_available": 81,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Black\"",
    "features": "\"White\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "c2018722-9a65-481c-bae8-be72a0293fcc"
  },
  {
    "name": "Shirts Product 5",
    "description": "Description for Shirts Product 5",
    "price": 535.77,
    "rating": 3.7,
    "brand": "Brand for Shirts Product 5",
    "images": "'[\"/images/shirts5_1.jpg\"",
    "stock_quantity": "\"/images/shirts5_2.jpg\"]'",
    "colors_available": 17,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"XL\"",
    "availability": "\"S\"]'",
    "subcategoryId": "c2018722-9a65-481c-bae8-be72a0293fcc"
  },
  {
    "name": "Trousers Product 1",
    "description": "Description for Trousers Product 1",
    "price": 561.03,
    "rating": 3.1,
    "brand": "Brand for Trousers Product 1",
    "images": "'[\"/images/trousers1_1.jpg\"",
    "stock_quantity": "\"/images/trousers1_2.jpg\"]'",
    "colors_available": 90,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Red\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "817cb926-e902-4e94-913f-bec0c9f27ea2"
  },
  {
    "name": "Trousers Product 2",
    "description": "Description for Trousers Product 2",
    "price": 566.82,
    "rating": 4.9,
    "brand": "Brand for Trousers Product 2",
    "images": "'[\"/images/trousers2_1.jpg\"",
    "stock_quantity": "\"/images/trousers2_2.jpg\"]'",
    "colors_available": 50,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "817cb926-e902-4e94-913f-bec0c9f27ea2"
  },
  {
    "name": "Trousers Product 3",
    "description": "Description for Trousers Product 3",
    "price": 963.92,
    "rating": 3.9,
    "brand": "Brand for Trousers Product 3",
    "images": "'[\"/images/trousers3_1.jpg\"",
    "stock_quantity": "\"/images/trousers3_2.jpg\"]'",
    "colors_available": 80,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"L\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "817cb926-e902-4e94-913f-bec0c9f27ea2"
  },
  {
    "name": "Trousers Product 4",
    "description": "Description for Trousers Product 4",
    "price": 664.85,
    "rating": 3.2,
    "brand": "Brand for Trousers Product 4",
    "images": "'[\"/images/trousers4_1.jpg\"",
    "stock_quantity": "\"/images/trousers4_2.jpg\"]'",
    "colors_available": 75,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"XL\"",
    "availability": "\"S\"]'",
    "subcategoryId": "817cb926-e902-4e94-913f-bec0c9f27ea2"
  },
  {
    "name": "Trousers Product 5",
    "description": "Description for Trousers Product 5",
    "price": 823.7,
    "rating": 4.2,
    "brand": "Brand for Trousers Product 5",
    "images": "'[\"/images/trousers5_1.jpg\"",
    "stock_quantity": "\"/images/trousers5_2.jpg\"]'",
    "colors_available": 14,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"M\"",
    "availability": "\"L\"]'",
    "subcategoryId": "817cb926-e902-4e94-913f-bec0c9f27ea2"
  },
  {
    "name": "Shoes Product 1",
    "description": "Description for Shoes Product 1",
    "price": 70.38,
    "rating": 3.3,
    "brand": "Brand for Shoes Product 1",
    "images": "'[\"/images/shoes1_1.jpg\"",
    "stock_quantity": "\"/images/shoes1_2.jpg\"]'",
    "colors_available": 20,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"Black\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "a5b8b65c-ff31-4070-b4dd-9c3c68119391"
  },
  {
    "name": "Shoes Product 2",
    "description": "Description for Shoes Product 2",
    "price": 11.52,
    "rating": 2.8,
    "brand": "Brand for Shoes Product 2",
    "images": "'[\"/images/shoes2_1.jpg\"",
    "stock_quantity": "\"/images/shoes2_2.jpg\"]'",
    "colors_available": 31,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"XL\"",
    "availability": "\"S\"]'",
    "subcategoryId": "a5b8b65c-ff31-4070-b4dd-9c3c68119391"
  },
  {
    "name": "Shoes Product 3",
    "description": "Description for Shoes Product 3",
    "price": 25.61,
    "rating": 4.6,
    "brand": "Brand for Shoes Product 3",
    "images": "'[\"/images/shoes3_1.jpg\"",
    "stock_quantity": "\"/images/shoes3_2.jpg\"]'",
    "colors_available": 41,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"White\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "a5b8b65c-ff31-4070-b4dd-9c3c68119391"
  },
  {
    "name": "Shoes Product 4",
    "description": "Description for Shoes Product 4",
    "price": 71.3,
    "rating": 3.6,
    "brand": "Brand for Shoes Product 4",
    "images": "'[\"/images/shoes4_1.jpg\"",
    "stock_quantity": "\"/images/shoes4_2.jpg\"]'",
    "colors_available": 78,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Green\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",
    "subcategoryId": "a5b8b65c-ff31-4070-b4dd-9c3c68119391"
  },
  {
    "name": "Shoes Product 5",
    "description": "Description for Shoes Product 5",
    "price": 270.9,
    "rating": 2.9,
    "brand": "Brand for Shoes Product 5",
    "images": "'[\"/images/shoes5_1.jpg\"",
    "stock_quantity": "\"/images/shoes5_2.jpg\"]'",
    "colors_available": 77,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"L\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "a5b8b65c-ff31-4070-b4dd-9c3c68119391"
  },
  {
    "name": "Dresses Product 1",
    "description": "Description for Dresses Product 1",
    "price": 345.55,
    "rating": 4.0,
    "brand": "Brand for Dresses Product 1",
    "images": "'[\"/images/dresses1_1.jpg\"",
    "stock_quantity": "\"/images/dresses1_2.jpg\"]'",
    "colors_available": 70,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"Red\"",
    "features": "\"White\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"L\"]'",
    "subcategoryId": "c1473948-5526-49b1-892c-7995b9d57bd2"
  },
  {
    "name": "Dresses Product 2",
    "description": "Description for Dresses Product 2",
    "price": 193.15,
    "rating": 4.1,
    "brand": "Brand for Dresses Product 2",
    "images": "'[\"/images/dresses2_1.jpg\"",
    "stock_quantity": "\"/images/dresses2_2.jpg\"]'",
    "colors_available": 32,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",
    "subcategoryId": "c1473948-5526-49b1-892c-7995b9d57bd2"
  },
  {
    "name": "Dresses Product 3",
    "description": "Description for Dresses Product 3",
    "price": 645.98,
    "rating": 3.8,
    "brand": "Brand for Dresses Product 3",
    "images": "'[\"/images/dresses3_1.jpg\"",
    "stock_quantity": "\"/images/dresses3_2.jpg\"]'",
    "colors_available": 50,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"White\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "c1473948-5526-49b1-892c-7995b9d57bd2"
  },
  {
    "name": "Dresses Product 4",
    "description": "Description for Dresses Product 4",
    "price": 533.96,
    "rating": 5.0,
    "brand": "Brand for Dresses Product 4",
    "images": "'[\"/images/dresses4_1.jpg\"",
    "stock_quantity": "\"/images/dresses4_2.jpg\"]'",
    "colors_available": 60,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Red\"",
    "features": "\"White\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "c1473948-5526-49b1-892c-7995b9d57bd2"
  },
  {
    "name": "Dresses Product 5",
    "description": "Description for Dresses Product 5",
    "price": 187.37,
    "rating": 4.9,
    "brand": "Brand for Dresses Product 5",
    "images": "'[\"/images/dresses5_1.jpg\"",
    "stock_quantity": "\"/images/dresses5_2.jpg\"]'",
    "colors_available": 16,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "c1473948-5526-49b1-892c-7995b9d57bd2"
  },
  {
    "name": "Skirts Product 1",
    "description": "Description for Skirts Product 1",
    "price": 98.44,
    "rating": 4.5,
    "brand": "Brand for Skirts Product 1",
    "images": "'[\"/images/skirts1_1.jpg\"",
    "stock_quantity": "\"/images/skirts1_2.jpg\"]'",
    "colors_available": 76,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"White\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"XL\"",
    "availability": "\"S\"]'",
    "subcategoryId": "c28e3686-4dd8-40da-a417-d9e47c03d03e"
  },
  {
    "name": "Skirts Product 2",
    "description": "Description for Skirts Product 2",
    "price": 33.47,
    "rating": 2.6,
    "brand": "Brand for Skirts Product 2",
    "images": "'[\"/images/skirts2_1.jpg\"",
    "stock_quantity": "\"/images/skirts2_2.jpg\"]'",
    "colors_available": 36,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"M\"",
    "availability": "\"S\"]'",
    "subcategoryId": "c28e3686-4dd8-40da-a417-d9e47c03d03e"
  },
  {
    "name": "Skirts Product 3",
    "description": "Description for Skirts Product 3",
    "price": 102.1,
    "rating": 4.7,
    "brand": "Brand for Skirts Product 3",
    "images": "'[\"/images/skirts3_1.jpg\"",
    "stock_quantity": "\"/images/skirts3_2.jpg\"]'",
    "colors_available": 48,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"White\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"L\"]'",
    "subcategoryId": "c28e3686-4dd8-40da-a417-d9e47c03d03e"
  },
  {
    "name": "Skirts Product 4",
    "description": "Description for Skirts Product 4",
    "price": 233.07,
    "rating": 2.8,
    "brand": "Brand for Skirts Product 4",
    "images": "'[\"/images/skirts4_1.jpg\"",
    "stock_quantity": "\"/images/skirts4_2.jpg\"]'",
    "colors_available": 56,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Green\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",
    "subcategoryId": "c28e3686-4dd8-40da-a417-d9e47c03d03e"
  },
  {
    "name": "Skirts Product 5",
    "description": "Description for Skirts Product 5",
    "price": 419.37,
    "rating": 3.9,
    "brand": "Brand for Skirts Product 5",
    "images": "'[\"/images/skirts5_1.jpg\"",
    "stock_quantity": "\"/images/skirts5_2.jpg\"]'",
    "colors_available": 97,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"M\"",
    "availability": "\"S\"]'",
    "subcategoryId": "c28e3686-4dd8-40da-a417-d9e47c03d03e"
  },
  {
    "name": "Handbags Product 1",
    "description": "Description for Handbags Product 1",
    "price": 474.87,
    "rating": 3.2,
    "brand": "Brand for Handbags Product 1",
    "images": "'[\"/images/handbags1_1.jpg\"",
    "stock_quantity": "\"/images/handbags1_2.jpg\"]'",
    "colors_available": 31,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Red\"",
    "features": "\"White\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"M\"",
    "availability": "\"S\"]'",
    "subcategoryId": "81768e3d-9daf-5239-85aa-2ef1abd4a21e"
  },
  {
    "name": "Handbags Product 2",
    "description": "Description for Handbags Product 2",
    "price": 191.54,
    "rating": 3.4,
    "brand": "Brand for Handbags Product 2",
    "images": "'[\"/images/handbags2_1.jpg\"",
    "stock_quantity": "\"/images/handbags2_2.jpg\"]'",
    "colors_available": 13,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"M\"",
    "availability": "\"L\"]'",
    "subcategoryId": "81768e3d-9daf-5239-85aa-2ef1abd4a21e"
  },
  {
    "name": "Handbags Product 3",
    "description": "Description for Handbags Product 3",
    "price": 980.75,
    "rating": 4.1,
    "brand": "Brand for Handbags Product 3",
    "images": "'[\"/images/handbags3_1.jpg\"",
    "stock_quantity": "\"/images/handbags3_2.jpg\"]'",
    "colors_available": 12,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"White\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "81768e3d-9daf-5239-85aa-2ef1abd4a21e"
  },
  {
    "name": "Handbags Product 4",
    "description": "Description for Handbags Product 4",
    "price": 79.59,
    "rating": 4.6,
    "brand": "Brand for Handbags Product 4",
    "images": "'[\"/images/handbags4_1.jpg\"",
    "stock_quantity": "\"/images/handbags4_2.jpg\"]'",
    "colors_available": 75,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Green\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",
    "subcategoryId": "81768e3d-9daf-5239-85aa-2ef1abd4a21e"
  },
  {
    "name": "Handbags Product 5",
    "description": "Description for Handbags Product 5",
    "price": 915.32,
    "rating": 3.9,
    "brand": "Brand for Handbags Product 5",
    "images": "'[\"/images/handbags5_1.jpg\"",
    "stock_quantity": "\"/images/handbags5_2.jpg\"]'",
    "colors_available": 69,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "81768e3d-9daf-5239-85aa-2ef1abd4a21e"
  },
  {
    "name": "T-Shirts Product 1",
    "description": "Description for T-Shirts Product 1",
    "price": 633.37,
    "rating": 3.2,
    "brand": "Brand for T-Shirts Product 1",
    "images": "'[\"/images/t-shirts1_1.jpg\"",
    "stock_quantity": "\"/images/t-shirts1_2.jpg\"]'",
    "colors_available": 38,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"White\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"M\"",
    "availability": "\"S\"]'",
    "subcategoryId": "76c42a90-1d54-494b-8579-6ac6f4531548"
  },
  {
    "name": "T-Shirts Product 2",
    "description": "Description for T-Shirts Product 2",
    "price": 134.04,
    "rating": 4.7,
    "brand": "Brand for T-Shirts Product 2",
    "images": "'[\"/images/t-shirts2_1.jpg\"",
    "stock_quantity": "\"/images/t-shirts2_2.jpg\"]'",
    "colors_available": 28,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"M\"",
    "availability": "\"L\"]'",
    "subcategoryId": "76c42a90-1d54-494b-8579-6ac6f4531548"
  },
  {
    "name": "T-Shirts Product 3",
    "description": "Description for T-Shirts Product 3",
    "price": 64.5,
    "rating": 4.5,
    "brand": "Brand for T-Shirts Product 3",
    "images": "'[\"/images/t-shirts3_1.jpg\"",
    "stock_quantity": "\"/images/t-shirts3_2.jpg\"]'",
    "colors_available": 74,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"White\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"M\"",
    "availability": "\"XL\"]'",
    "subcategoryId": "76c42a90-1d54-494b-8579-6ac6f4531548"
  },
  {
    "name": "T-Shirts Product 4",
    "description": "Description for T-Shirts Product 4",
    "price": 365.36,
    "rating": 4.8,
    "brand": "Brand for T-Shirts Product 4",
    "images": "'[\"/images/t-shirts4_1.jpg\"",
    "stock_quantity": "\"/images/t-shirts4_2.jpg\"]'",
    "colors_available": 53,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Black\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"S\"",
    "availability": "\"M\"]'",
    "subcategoryId": "76c42a90-1d54-494b-8579-6ac6f4531548"
  },
  {
    "name": "T-Shirts Product 5",
    "description": "Description for T-Shirts Product 5",
    "price": 521.37,
    "rating": 3.6,
    "brand": "Brand for T-Shirts Product 5",
    "images": "'[\"/images/t-shirts5_1.jpg\"",
    "stock_quantity": "\"/images/t-shirts5_2.jpg\"]'",
    "colors_available": 52,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Black\"",
    "features": "\"White\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "76c42a90-1d54-494b-8579-6ac6f4531548"
  },
  {
    "name": "Shorts Product 1",
    "description": "Description for Shorts Product 1",
    "price": 305.45,
    "rating": 4.3,
    "brand": "Brand for Shorts Product 1",
    "images": "'[\"/images/shorts1_1.jpg\"",
    "stock_quantity": "\"/images/shorts1_2.jpg\"]'",
    "colors_available": 25,
    "sizes_available": "'[\"Green\"",
    "shipping_info": "\"White\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"L\"",
    "availability": "\"XL\"]'",
    "categoryId": "89a0f9e2-3706-4813-931c-df31bfb714fe",
    "subcategoryId": "d7cc4a3f-0cf5-427c-af95-f6596bea24f0"
  },
  {
    "name": "Shorts Product 2",
    "description": "Description for Shorts Product 2",
    "price": 566.96,
    "rating": 4.0,
    "brand": "Brand for Shorts Product 2",
    "images": "'[\"/images/shorts2_1.jpg\"",
    "stock_quantity": "\"/images/shorts2_2.jpg\"]'",
    "colors_available": 33,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Red\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"L\"",
    "additional_info": "\"M\"",
    "availability": "\"XL\"]'",    "categoryId": "89a0f9e2-3706-4813-931c-df31bfb714fe",

    "subcategoryId": "d7cc4a3f-0cf5-427c-af95-f6596bea24f0"
  },
  {
    "name": "Shorts Product 3",
    "description": "Description for Shorts Product 3",
    "price": 433.83,
    "rating": 4.4,
    "brand": "Brand for Shorts Product 3",
    "images": "'[\"/images/shorts3_1.jpg\"",
    "stock_quantity": "\"/images/shorts3_2.jpg\"]'",
    "colors_available": 24,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Red\"",
    "features": "\"Green\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"S\"",
    "availability": "\"L\"]'",    "categoryId": "89a0f9e2-3706-4813-931c-df31bfb714fe",

    "subcategoryId": "d7cc4a3f-0cf5-427c-af95-f6596bea24f0"
  },
  {
    "name": "Shorts Product 4",
    "description": "Description for Shorts Product 4",
    "price": 117.93,
    "rating": 3.9,
    "brand": "Brand for Shorts Product 4",
    "images": "'[\"/images/shorts4_1.jpg\"",
    "stock_quantity": "\"/images/shorts4_2.jpg\"]'",
    "colors_available": 27,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Green\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"S\"",
    "availability": "\"L\"]'",    "categoryId": "89a0f9e2-3706-4813-931c-df31bfb714fe",

    "subcategoryId": "d7cc4a3f-0cf5-427c-af95-f6596bea24f0"
  },
  {
    "name": "Shorts Product 5",
    "description": "Description for Shorts Product 5",
    "price": 298.05,
    "rating": 3.5,
    "brand": "Brand for Shorts Product 5",
    "images": "'[\"/images/shorts5_1.jpg\"",
    "stock_quantity": "\"/images/shorts5_2.jpg\"]'",
    "colors_available": 89,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Blue\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"S\"",
    "availability": "\"XL\"]'",    "categoryId": "89a0f9e2-3706-4813-931c-df31bfb714fe",

    "subcategoryId": "d7cc4a3f-0cf5-427c-af95-f6596bea24f0"
  },
  {
    "name": "Sneakers Product 1",
    "description": "Description for Sneakers Product 1",
    "price": 330.7,
    "rating": 4.5,
    "brand": "Brand for Sneakers Product 1",
    "images": "'[\"/images/sneakers1_1.jpg\"",
    "stock_quantity": "\"/images/sneakers1_2.jpg\"]'",
    "colors_available": 61,
    "sizes_available": "'[\"Red\"",
    "shipping_info": "\"White\"",
    "features": "\"Blue\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"L\"]'",
    "subcategoryId": "c7f3ed24-ac42-5fbe-a375-96dc77fc1681"
  },
  {
    "name": "Sneakers Product 2",
    "description": "Description for Sneakers Product 2",
    "price": 504.92,
    "rating": 3.8,
    "brand": "Brand for Sneakers Product 2",
    "images": "'[\"/images/sneakers2_1.jpg\"",
    "stock_quantity": "\"/images/sneakers2_2.jpg\"]'",
    "colors_available": 94,
    "sizes_available": "'[\"Black\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "9b1b867f-b031-4e1a-a491-9d1dc3853913"
  },
  {
    "name": "Sneakers Product 3",
    "description": "Description for Sneakers Product 3",
    "price": 26.6,
    "rating": 3.9,
    "brand": "Brand for Sneakers Product 3",
    "images": "'[\"/images/sneakers3_1.jpg\"",
    "stock_quantity": "\"/images/sneakers3_2.jpg\"]'",
    "colors_available": 99,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"White\"",
    "features": "\"Red\"]'",
    "specifications": "'[\"M\"",
    "additional_info": "\"XL\"",
    "availability": "\"S\"]'",
    "subcategoryId": "9b1b867f-b031-4e1a-a491-9d1dc3853913"
  },
  {
    "name": "Sneakers Product 4",
    "description": "Description for Sneakers Product 4",
    "price": 630.58,
    "rating": 4.6,
    "brand": "Brand for Sneakers Product 4",
    "images": "'[\"/images/sneakers4_1.jpg\"",
    "stock_quantity": "\"/images/sneakers4_2.jpg\"]'",
    "colors_available": 36,
    "sizes_available": "'[\"Blue\"",
    "shipping_info": "\"Green\"",
    "features": "\"White\"]'",
    "specifications": "'[\"XL\"",
    "additional_info": "\"L\"",
    "availability": "\"M\"]'",
    "subcategoryId": "9b1b867f-b031-4e1a-a491-9d1dc3853913"
  },
  {
    "name": "Sneakers Product 5",
    "description": "Description for Sneakers Product 5",
    "price": 919.45,
    "rating": 3.8,
    "brand": "Brand for Sneakers Product 5",
    "images": "'[\"/images/sneakers5_1.jpg\"",
    "stock_quantity": "\"/images/sneakers5_2.jpg\"]'",
    "colors_available": 55,
    "sizes_available": "'[\"White\"",
    "shipping_info": "\"Red\"",
    "features": "\"Black\"]'",
    "specifications": "'[\"S\"",
    "additional_info": "\"XL\"",
    "availability": "\"M\"]'",
    "subcategoryId": "9b1b867f-b031-4e1a-a491-9d1dc3853913"
  }
];


async function seedProducts() {
  try {
    await client.connect();
    const db = client.db(dbName);

    // 🔥 Delete old products first
    await db.collection("products").deleteMany({});

    // 🚀 Insert new ones (UUID-based subcategoryId)
    await db.collection("products").insertMany(products);

    console.log("✅ Products seeded with subcategory links!");
  } catch (err) {
    console.error("❌ Product seeding failed:", err);
  } finally {
    await client.close();
  }
}

seedProducts();